#!/usr/bin/env python3
import os
PROFILE = """BASH_DIRNAME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PATH=${PATH}:${BASH_DIRNAME}/exp
"""
MAIN = """def main(*args):
    print('Hello World!')
"""
RUN = """#!/usr/bin/env python3
import os
import site
site.addsitedir(os.path.join(os.path.realpath(__file__), '..', '..'))
if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('args', nargs='*', help='Arguments passed to the function')
    parser.add_argument('-m', '--module', default='main', help='Module to execute [default: main]')
    parser.add_argument('-f', '--function', default='main', help='Function to execute [default: main]')
    args = parser.parse_args()
    getattr(__import__(args.module), args.function)(*args.args)
"""


def create_project(root):
    """create a project directory structure, as below:
        .
        ├── exp
        │ └── run
        ├── main.py
        └── profile
    """
    root = os.path.realpath(root)
    os.makedirs(root)
    profile_path = os.path.join(root, 'profile')
    with open(profile_path, mode='w') as f:
        f.write(PROFILE)
    main_path = os.path.join(root, 'main.py')
    with open(main_path, mode='w') as f:
        f.write(MAIN)
    os.mkdir(os.path.join(root, 'exp'))
    run_path = os.path.join(root, 'exp', 'run')
    with open(run_path, mode='w') as f:
        f.write(RUN)
    os.system(f'chmod 775 {run_path}')


if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('path', nargs=1, help='Project root directory')
    args = parser.parse_args()
    create_project(args.path[0])
